"""Renderers: turn a :class:`CompiledScript` or the model into an output format.

Formats:

* ``json``          — the fully resolved flow object (no MCP wrapper).
* ``playwright-mcp`` — the same, each step annotated with its exact MCP tool+args.
* ``steps``         — a compact ``op``/``selector``/``value`` list for other executors.
* ``pw-test``       — a real ``@playwright/test`` spec.
* ``pw-pom``        — Python Page Object Model classes generated from the YAML
                      (build artifacts; never hand-edited — design DEC-UICLI-6).
"""

from __future__ import annotations

import json
from typing import Optional

from uipilot.domain.compiler import CompiledScript
from uipilot.domain.model import Element, Pack, Selector

# ---------------------------------------------------------------------------
# Script renderers
# ---------------------------------------------------------------------------


def to_json(script: CompiledScript) -> str:
    return json.dumps(script.as_dict(with_mcp=False), indent=2)


def to_playwright_mcp(script: CompiledScript) -> str:
    return json.dumps(script.as_dict(with_mcp=True), indent=2)


def to_steps(script: CompiledScript) -> str:
    rows = []
    for step in script.steps:
        row = {"n": step.n, "op": step.op}
        if step.selector:
            row["selector"] = step.selector
        if step.value is not None:
            row["value"] = step.value
        if step.capture:
            row["capture"] = step.capture
        rows.append(row)
    return json.dumps({
        "flow": script.name,
        "preconditions": script.preconditions,
        "steps": rows,
    }, indent=2)


# ---------------------------------------------------------------------------
# Playwright locator helpers (from a selector dict on a compiled step)
# ---------------------------------------------------------------------------


def _selector_from_dict(raw: dict) -> Selector:
    strategy = raw.get("strategy")
    if not strategy:
        if raw.get("role"):
            strategy = "role"
        elif raw.get("css"):
            strategy = "css"
        elif raw.get("text"):
            strategy = "text"
        elif raw.get("label"):
            strategy = "label"
        elif raw.get("testid"):
            strategy = "testid"
        else:
            strategy = "css"
    return Selector(strategy=strategy, role=raw.get("role"), name=raw.get("name"),
                    text=raw.get("text"), label=raw.get("label"), css=raw.get("css"),
                    testid=raw.get("testid"), scope=raw.get("scope"),
                    exact=raw.get("exact"))


def _py_locator(sel: Selector) -> str:
    def _q(v: str) -> str:
        return '"' + (v or "").replace("\\", "\\\\").replace('"', '\\"') + '"'

    if sel.strategy == "role":
        extra = f", name={_q(sel.name)}" if sel.name else ""
        if sel.exact:
            extra += ", exact=True"
        base = f'get_by_role({_q(sel.role or "")}{extra})'
    elif sel.strategy == "label":
        base = f'get_by_label({_q(sel.label or sel.name or "")})'
    elif sel.strategy == "text":
        base = f'get_by_text({_q(sel.text or sel.name or "")})'
    elif sel.strategy == "testid":
        base = f'get_by_test_id({_q(sel.testid or "")})'
    else:
        base = f'locator({_q(sel.css or "")})'
    if sel.scope:
        return f'get_by_role({_q(sel.scope)}).{base}'
    return base


# ---------------------------------------------------------------------------
# @playwright/test spec
# ---------------------------------------------------------------------------


def to_pw_test(script: CompiledScript) -> str:
    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// Generated by uipilot from flow '{script.name}'. Do not hand-edit.",
        f"// requires_auth: {', '.join(script.requires_auth) or 'none'}"
        f"  risk_max: {script.risk_max}",
    ]
    for pre in script.preconditions:
        lines.append(f"//   precondition: {pre.get('kind')} {pre.get('id') or pre.get('flow') or ''}")
    lines.append("")
    lines.append(f"test({_js(script.name)}, async ({{ page }}) => {{")
    for step in script.steps:
        lines.append("  " + _pw_line(step))
    for cc in script.crosschecks:
        lines.append(f"  // crosscheck: {cc.get('id')} -> {cc.get('call')}")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _js(value: str) -> str:
    return "'" + (value or "").replace("\\", "\\\\").replace("'", "\\'") + "'"


def _pw_line(step) -> str:
    op = step.op
    if op == "navigate":
        return f"await page.goto({_js(step.value or '')});"
    if op == "snapshot":
        return "// snapshot (implicit in @playwright/test)"
    loc = f"page.{_py_to_js(step.selector)}" if step.selector else "page"
    if op == "click":
        return f"await {loc}.click();"
    if op in ("fill", "type"):
        return f"await {loc}.fill({_js(step.value or '')});"
    if op == "select":
        return f"await {loc}.selectOption({_js(step.value or '')});"
    if op == "press":
        return f"await page.keyboard.press({_js(step.value or '')});"
    if op == "wait_for":
        text = (step.mcp or {}).get("args", {}).get("text") if step.mcp else None
        if text:
            return f"await expect(page.getByText({_js(text)})).toBeVisible();"
        return "// wait_for"
    if op == "expect":
        return f"await expect({loc}).toBeVisible();"
    if op == "capture":
        return f"// capture {step.capture} from {step.from_}"
    if op == "upload":
        return f"await {loc}.setInputFiles({_js(step.value or '')});"
    if op == "fill_form":
        return f"// fill_form ({step.note})"
    return f"// {op}"


def _py_to_js(selector_dict: dict) -> str:
    """Render a selector dict to a JS locator (getByRole(...))."""
    return _selector_from_dict(selector_dict).to_locator()


# ---------------------------------------------------------------------------
# Python POM generation
# ---------------------------------------------------------------------------


def render_pw_pom(pack: Pack, app_id: Optional[str] = None) -> str:
    apps = [app_id] if app_id else list(pack.apps)
    out = [
        '"""Generated Page Object Model classes. DO NOT EDIT.',
        "",
        "Regenerated from the uipilot YAML via `uipilot emit --format pw-pom`.",
        "The YAML is the single selector source; hand-editing here is forbidden.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from playwright.sync_api import Page",
        "",
    ]
    for aid in apps:
        app = pack.app(aid)
        if app is None:
            continue
        class_name = _class_name(aid)
        out.append(f"class {class_name}:")
        out.append(f'    """Page object for app \'{aid}\'."""')
        out.append("")
        out.append("    def __init__(self, page: Page) -> None:")
        out.append("        self.page = page")
        out.append("")
        elements = sorted(
            (e for e in pack.elements.values() if e.app == aid),
            key=lambda e: e.id,
        )
        for el in elements:
            method = _element_method(el, app.id_prefix)
            if el.purpose:
                out.append(f"    # {el.purpose}")
            out.append("    @property")
            out.append(f"    def {method}(self):")
            out.append(f"        return self.page.{_py_locator(el.selector)}")
            out.append("")
        out.append("")
    return "\n".join(out)


def _class_name(app_id: str) -> str:
    return "".join(part.capitalize() for part in app_id.replace("-", "_").split("_")) + "Page"


def _element_method(el: Element, id_prefix: str) -> str:
    name = el.id
    for pref in (f"{id_prefix}_", f"{el.app}_"):
        if name.startswith(pref):
            name = name[len(pref):]
            break
    return name or el.id
